---
legislation:
  - ATEX 2016
  - Aerosol Dispensers Regulations 2009 (Consumer Protection Act 1987)
  - Cableway Installations Regulations 2018
  - Carriage of Dangerous Goods and Use of Transportable Pressure Equipment Regulations 2009
  - Classification, Labelling and Packaging of Chemicals Regulations 2015
  - Construction Products Regulations 2013
  - Consumer Protection Act 1987
  - Consumer Protection Act 1987 / Motor Vehicle Tyres (Safety) Regulations 1994
  - Cosmetic Products Enforcement Regulations 2013
  - EC Fertilisers (England and Wales) Regulations 2006
  - Ecodesign for Energy-Related Products Regulations 2010
  - Electrical Equipment (Safety) Regulations 2016
  - Electromagnetic Compatibility Regulations 2016
  - End-of-Life Vehicles Regulations 2003 (as amended)
  - Energy Information Regulations 2011
  - Explosives Regulations 2014
  - Fireworks Act 2003 / Fireworks Regulations 2004
  - Food Imitations (Safety) Regulations 1989
  - Furniture and Furnishings (Fire) (Safety) Regulations 1988
  - Gas Appliances (Enforcement) and Miscellaneous Amendments Regulations 2018
  - General Product Safety Regulations 2005
  - Gun Barrel Proof Acts 1868 to 1978
  - Lifts Regulations 2016
  - Measuring Instruments Regulations 2016
  - Measuring Instruments Regulations 2016 (also NAWI)
  - Medical Devices Regulations 2002
  - Merchant Shipping (Marine Equipment) Regulations 2016
  - Motor Vehicle Tyres (Safety) Regulations 1994 (Consumer Protection Act 1987)
  - N-nitrosamines and N-nitrosatable Substances in Elastomer or Rubber Teats and Dummies (Safety) Regulations 1995
  - Nightwear (Safety) Regulations 1985
  - Noise Emission in the Environment by Equipment for use Outdoors Regulations 2001 (as amended)
  - Non-Automatic Weighing Instruments Regulations 2016
  - Oil Heaters (Safety) Regulations 1977
  - Personal Protective Equipment (Enforcement) Regulations 2018
  - Plugs and Sockets etc. (Safety) Regulations 1994
  - Pressure Equipment (Safety) Regulations 2016
  - Pyrotechnic Articles (Safety) Regulations 2015
  - REACH Enforcement Regulations 2008
  - Radio Equipment Regulations 2017
  - Recreational Craft Regulations 2017
  - Restriction of Use of Certain Hazardous Substances in Electrical and Electronic Equipment Regulations 2012
  - Simple Pressure Vessels (Safety) Regulations 2016
  - Supply of Machinery (Safety) Regulations 2008
  - Textile Products (Labelling and Fibre Composition) Regulations 2012
  - Toys (Safety) Regulations 2011 (Consumer Protection Act 1987)
  - Weights and Measures (Packaged Goods) Regulations (Northern Ireland) 2011
  - Weights and Measures (Packaged Goods) Regulations 2006
