---
email_domains:
  - "aberdeencity.gov.uk"
  - "aberdeenshire.gov.uk"
  - "angus.gov.uk"
  - "antrimandnewtownabbey.gov.uk"
  - "ardsandnorthdown.gov.uk"
  - "argyll-bute.gov.uk"
  - "armaghbanbridgecraigavon.gov.uk"
  - "barnet.gov.uk"
  - "barnsley.gov.uk"
  - "bathnes.gov.uk"
  - "bcpcouncil.gov.uk"
  - "bedford.gov.uk"
  - "beis.gov.uk"
  - "BelfastCity.gov.uk"
  - "bexley.gov.uk"
  - "birmingham.gov.uk"
  - "blackburn.gov.uk"
  - "blackpool.gov.uk"
  - "blaenau-gwent.gov.uk"
  - "bolton.gov.uk"
  - "brent.gov.uk"
  - "brighton-hove.gov.uk"
  - "bristol.gov.uk"
  - "bromley.gov.uk"
  - "bury.gov.uk"
  - "businessandtrade.gov.uk"
  - "caerphilly.gov.uk"
  - "cambridgeshire.gov.uk"
  - "camden.gov.uk"
  - "carmarthenshire.gov.uk"
  - "causewaycoastandglens.gov.uk"
  - "centralbedfordshire.gov.uk"
  - "ceredigion.gov.uk"
  - "cheshireeast.gov.uk"
  - "cheshirewestandchester.gov.uk"
  - "cityoflondon.gov.uk"
  - "cne-siar.gov.uk"
  - "conwy.gov.uk"
  - "cornwall.gov.uk"
  - "coventry.gov.uk"
  - "croydon.gov.uk"
  - "cumbria.gov.uk"
  - "daera-ni.gov.uk"
  - "darlington.gov.uk"
  - "denbighshire.gov.uk"
  - "derby.gov.uk"
  - "derbyshire.gov.uk"
  - "derrystrabane.com"
  - "devon.gov.uk"
  - "doncaster.gov.uk"
  - "dorsetcouncil.gov.uk"
  - "dudley.gov.uk"
  - "dumgal.gov.uk"
  - "dundeecity.gov.uk"
  - "durham.gov.uk"
  - "dvsa.gov.uk"
  - "ealing.gov.uk"
  - "east-ayrshire.gov.uk"
  - "eastdunbarton.gov.uk"
  - "eastlothian.gov.uk"
  - "eastrenfrewshire.gov.uk"
  - "eastriding.gov.uk"
  - "eastsussex.gov.uk"
  - "economy-ni.gov.uk"
  - "edinburgh.gov.uk"
  - "enfield.gov.uk"
  - "essex.gov.uk"
  - "falkirk.gov.uk"
  - "fermanaghomagh.com"
  - "fife.gov.uk"
  - "flintshire.gov.uk"
  - "Gateshead.Gov.UK"
  - "glasgow.gov.uk"
  - "gloucestershire.gov.uk"
  - "gwynedd.llyw.cymru"
  - "hackney.gov.uk"
  - "halton.gov.uk"
  - "hants.gov.uk"
  - "haringey.gov.uk"
  - "hartlepool.gov.uk"
  - "havering.gov.uk"
  - "herefordshire.gov.uk"
  - "hertfordshire.gov.uk"
  - "highland.gov.uk"
  - "hillingdon.gov.uk"
  - "hounslow.gov.uk"
  - "hse.gov.uk"
  - "hseni.gov.uk"
  - "hullcc.gov.uk"
  - "inverclyde.gov.uk"
  - "iow.gov.uk"
  - "islington.gov.uk"
  - "justice-ni.gov.uk"
  - "kent.gov.uk"
  - "kingston.gov.uk"
  - "knowsley.gov.uk"
  - "lambeth.gov.uk"
  - "lancashire.gov.uk"
  - "lbbd.gov.uk"
  - "lbhf.gov.uk"
  - "leicester.gov.uk"
  - "leics.gov.uk"
  - "lewisham.gov.uk"
  - "lincolnshire.gov.uk"
  - "lisburncastlereagh.gov.uk"
  - "liverpool.gov.uk"
  - "luton.gov.uk"
  - "manchester.gov.uk"
  - "mcga.gov.uk"
  - "medway.gov.uk"
  - "merthyr.gov.uk"
  - "merton.gov.uk"
  - "mhra.gov.uk"
  - "midandeastantrim.gov.uk"
  - "middlesbrough.gov.uk"
  - "midlothian.gov.uk"
  - "midulstercouncil.org"
  - "milton-keynes.gov.uk"
  - "monmouthshire.gov.uk"
  - "moray.gov.uk"
  - "n-somerset.gov.uk"
  - "nelincs.gov.uk"
  - "newcastle.gov.uk"
  - "newham.gov.uk"
  - "newport.gov.uk"
  - "nmandd.org"
  - "norfolk.gov.uk"
  - "north-ayrshire.gov.uk"
  - "northamptonshire.gov.uk"
  - "northlan.gov.uk"
  - "northlincs.gov.uk"
  - "northnorthants.gov.uk"
  - "northtyneside.gov.uk"
  - "northumberland.gov.uk"
  - "northyorks.gov.uk"
  - "nottinghamcity.gov.uk"
  - "nottscc.gov.uk"
  - "npt.gov.uk"
  - "ofcom.org.uk"
  - "oldham.gov.uk"
  - "orkney.gov.uk"
  - "oxfordshire.gov.uk"
  - "pembrokeshire.gov.uk"
  - "peterborough.gov.uk"
  - "pkc.gov.uk"
  - "plymouth.gov.uk"
  - "portsmouthcc.gov.uk"
  - "powys.gov.uk"
  - "rbkc.gov.uk"
  - "RBWM.gov.uk"
  - "rctcbc.gov.uk"
  - "reading.gov.uk"
  - "redbridge.gov.uk"
  - "redcar-cleveland.gov.uk"
  - "renfrewshire.gov.uk"
  - "rochdale.gov.uk"
  - "rotherham.gov.uk"
  - "royalgreenwich.gov.uk"
  - "salford.gov.uk"
  - "sandwell.gov.uk"
  - "scotborders.gov.uk"
  - "sefton.gov.uk"
  - "sheffield.gov.uk"
  - "shetland.gov.uk"
  - "shropshire.gov.uk"
  - "slough.gov.uk"
  - "solihull.gov.uk"
  - "south-ayrshire.gov.uk"
  - "southampton.gov.uk"
  - "southend.gov.uk"
  - "southglos.gov.uk"
  - "southlanarkshire.gov.uk"
  - "southtyneside.gov.uk"
  - "southwark.gov.uk"
  - "staffordshire.gov.uk"
  - "sthelens.gov.uk"
  - "stirling.gov.uk"
  - "stockport.gov.uk"
  - "stockton.gov.uk"
  - "stoke.gov.uk"
  - "suffolk.gov.uk"
  - "sunderland.gov.uk"
  - "surreycc.gov.uk"
  - "sutton.gov.uk"
  - "swansea.gov.uk"
  - "swindon.gov.uk"
  - "tameside.gov.uk"
  - "telford.gov.uk"
  - "thurrock.gov.uk"
  - "torfaen.gov.uk"
  - "towerhamlets.gov.uk"
  - "trafford.gov.uk"
  - "valeofglamorgan.gov.uk"
  - "vca.gov.uk"
  - "walsall.gov.uk"
  - "walsall.gov.uk"
  - "walthamforest.gov.uk"
  - "warrington.gov.uk"
  - "warwickshire.gov.uk"
  - "west-dunbarton.gov.uk"
  - "westberks.gov.uk"
  - "westlothian.gov.uk"
  - "westminster.gov.uk"
  - "westnorthants.gov.uk"
  - "westsussex.gov.uk"
  - "wigan.gov.uk"
  - "wiltshire.gov.uk"
  - "wirral.gov.uk"
  - "wolverhampton.gov.uk"
  - "worcestershirets.gov.uk"
  - "wrexham.gov.uk"
  - "wyjs.org.uk"
  - "ynysmon.gov.uk"
  - "ynysmon.llyw.cymru"
  - "york.gov.uk"
