default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres@localhost:5432') %>
  pool: 5

development:
  <<: *default
  database: psd_development
test:
  <<: *default
  database: psd_test

production:
  url: <%= ENV.fetch('DATABASE_URL') %>
  connect_timeout: 2
  variables:
    statement_timeout: <%= ENV["STATEMENT_TIMEOUT"] || "500ms" %>
